name: Android Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install required NDK
      run: |
        echo "y" | sdkmanager "ndk;27.2.12479018"
        echo "y" | sdkmanager "cmake;3.22.1"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create dummy keystore
      run: |
        mkdir -p TMessagesProj/config
        keytool -genkey -v -keystore TMessagesProj/config/release.keystore \
          -alias naruto \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass 1111 \
          -keypass 1111 \
          -dname "CN=Android, OU=Android, O=Android, L=Unknown, ST=Unknown, C=US" \
          -noprompt

    - name: Build with Gradle
      env:
        RELEASE_STORE_PASSWORD: 1111
        RELEASE_KEY_PASSWORD: 1111
        RELEASE_KEY_ALIAS: naruto
      run: ./gradlew assembleStandaloneRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: telegram-apk
        path: TMessagesProj/build/outputs/apk/standaloneRelease/*.apk
